spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  ai:
    ollama:
      base-url: ${AFT_OLLAMA_URL:http://localhost:11434}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG

aft:
  jwt:
    secret: ${AFT_JWT_SECRET:}