package com.aft.api.common.audit;

public enum AuditAction {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGIN_BLOCKED,
    LOGOUT,
    PASSWORD_CHANGED,
    REFRESH_TOKEN_REUSE,
    USER_CREATED,
    USER_UPDATED,
    USER_DISABLED,
    ROLE_ASSIGNED,
    ROLE_REVOKED,
    API_KEY_CREATED,
    API_KEY_REVOKED,
    DEVICE_REGISTERED,
    DEVICE_REMOVED,
    DEVICE_CAPABILITIES_UPDATED,
    ORGANIZATION_CREATED,
    ORGANIZATION_UPDATED,
    MEMBER_INVITED,
    MEMBER_JOINED,
    MEMBER_REMOVED
}
